name: blazingsql_env
channels:
    - blazingsql
    - rapidsai
    - nvidia
    - conda-forge
dependencies:
    - blazingsql
    - cudatoolkit=11.4
    - flask=3.0.3
    - flask-restx=1.3.0
    - python-dotenv=1.0.1
    - pydash=8.0.3
    - openai
    - numpy=1.22  # Ensure compatibility with Cupy and CUDF
    - cython<0.30,>=0.29  # Required by cudf
    - cupy-cuda114  # Satisfy cudf and dask-cudf requirements
