name: blazingsql_env
channels:
    - blazingsql
    - rapidsai
    - nvidia
    - conda-forge
    - defaults
dependencies:
    - blazingsql
    - python=3.10
    - cudatoolkit=11.4
    - pip
    - pip:
          - Flask==3.0.3
          - flask-restx==1.3.0
          - python-dotenv==1.0.1
          - pydash==8.0.3
          - openai
